# Generated by Django 2.1.7 on 2019-12-20 01:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=50, unique=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('protools_vers', models.FloatField(default=18.4, verbose_name='ProTools Version')),
                ('number_of_systems', models.IntegerField(blank=True, null=True, verbose_name='Number of Systems')),
                ('drive_user', models.CharField(blank=True, max_length=50, verbose_name='Drive Username')),
                ('drive_pass', models.CharField(blank=True, max_length=50, verbose_name='Drive Password')),
                ('ms_user', models.CharField(blank=True, max_length=50, verbose_name='Media Shuttle Username')),
                ('ms_pass', models.CharField(blank=True, max_length=50, verbose_name='Media Shuttle Password')),
                ('channel_config', models.CharField(choices=[('ST', 'Stereo'), ('5.1', '5.1'), ('7.1', '7.1'), ('ATMOS', 'ATMOS'), ('DTS', 'DTS'), ('IMAX 6', 'IMAX 6'), ('IMAX 12', 'IMAX 12')], default='5.1', max_length=200, verbose_name='Channel Configuration')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Other Information')),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('mixing_complete_date', models.DateField(blank=True, null=True)),
                ('project_complete_date', models.DateField(blank=True, null=True)),
                ('mixing_completed_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_mixing_marked_completed', to=settings.AUTH_USER_MODEL)),
                ('project_complete_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_project_marked_completed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rentalproject',
            unique_together={('title', 'season', 'abbreviation', 'drive_user', 'drive_pass', 'ms_user', 'ms_pass')},
        ),
    ]
