# Generated by Django 2.1 on 2019-03-18 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproject',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
