# Generated by Django 3.0.1 on 2019-12-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalproject',
            name='files_link',
            field=models.URLField(blank=True, null=True, verbose_name='GoogleDrive Link'),
        ),
    ]
