# Generated by Django 3.0.2 on 2020-03-24 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_projects', '0003_auto_20200104_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalproject',
            name='protools_vers',
            field=models.FloatField(blank=True, null=True, verbose_name='ProTools Version'),
        ),
    ]
