# Generated by Django 2.1.7 on 2019-12-20 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_rooms', '__first__'),
        ('rental_projects', '__first__'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMediaShuttle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_ms', models.CharField(blank=True, max_length=50, verbose_name='IP')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_clients', to='rental_projects.RentalProject', verbose_name='project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_role', models.CharField(blank=True, choices=[('DX Mixer', 'DX Mixer'), ('MX Mixer', 'MX Mixer'), ('DX/MX Mixer', 'DX/MX Mixer'), ('FX Mixer', 'FX Mixer'), ('Recordist', 'Recordist'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Role')),
                ('notes', models.TextField(default=None, null=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_projects', to='contacts.Contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_clients', to='rental_projects.RentalProject')),
            ],
        ),
        migrations.AddField(
            model_name='clientmediashuttle',
            name='project_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_rooms', to='project_clients.ProjectClient', verbose_name='client'),
        ),
        migrations.AddField(
            model_name='clientmediashuttle',
            name='project_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ms_clients', to='project_rooms.ProjectRoom', verbose_name='room'),
        ),
        migrations.AlterUniqueTogether(
            name='projectclient',
            unique_together={('client', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='clientmediashuttle',
            unique_together={('project', 'client_ms')},
        ),
    ]
