# Generated by Django 2.1.7 on 2019-04-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectclient',
            name='notes',
            field=models.TextField(default=None, null=True, verbose_name='Notes'),
        ),
    ]
